var lang = [
    {
        "name":"Legend of Sea and Cloud",
        "starting_at":"Begins with",
        "start_a_journey_of_legend":"Open the legendary journey",
        "bind_success":"Binding succeeded",
        "bind_error":"Binding failed",
        "copy_success":"Copy is successful",
        "copy_error":"copy failed",
        "balance_not_enough":"Insufficient balance",
        "buy_error":"Purchase failed",
        "bind_parent":"Binding referrals",
        "my_parent":"My referrer",
        "please_enter_the_address_of_the_recommend":"Please enter a referral address",
        "bind_immediately":"Bind",
        "invite_friends":"Invite friends",
        "invitation_link":"Invitation link",
        "immediate_participation":"Immediately participate",
        "Investment_statement":"Investment daily static dividend 0.3-2.2%, recommended up to five times the income",
        "play":"participation",
        "available":"available",
        "send":"send",
        "burning_ratio":"current burning ratio",
        "rule_1":"This account will only accept the investment before the exit, and can continue to invest after the exit.",
        "rule_2":"Static dividends are floating up and down 0.3%~2.2% per day",
        "rule_3":"Stop and go out, according to 1-10 for investment amount 3 times, 11-30 for investment amount 4 times, greater than 31 for investment amount 5 times",
        "rule_4":"Dynamic recommendation 25% according to:10%->8%->7% to get dynamic rewards, you can withdraw cash immediately",
        "rule_5":"After the designated prize pool reaches the designated time, the prize pool will not settle until the lower wheel is opened",
        "rule_6":"After the designated prize pool has reached the specified time, it will not be deposited, and the investment amount will directly enter the dividend income.",
        "play_rule":"play rules",
        "sign_in_success":"Sign in to success",
        "sign_in_error":"checkin failed",
        "withdraw_success":"Calculate success",
        "withdraw_error":"Received Failed",
        "small_area_tip_1":"Sea area every",
        "small_area_tip_2":"The hour draws once, 100% open. Random 50 equals the prize pool.",
        "big_area_tip_1":"Cloud area per",
        "big_area_tip_2":"Hourly draw once, 100% open. One first prize directly wins 1/3 of the prize pool, second prize 10 equals 1/3 of the prize pool, third prize 20 points equals 1/3 of the prize pool ",
        "countdown_to_the_prize":"Countdown Countdown",
        "total_amount_of_prize_pool":"Total amount of prize pool",
        "buying_tickets":"Buy tickets",
        "purchase_admission_tickets":"Buy admission tickets",
        "purchase":"purchase",
        "data_statistics":"data statistics",
        "my_income":"My income",
        "settled_dividend_income":"Closed dividend income",
        "recommended_award":"Recommended reward",
        "bonus_pool_revenue":"Palace revenue",
        "time_difference_of_next_dividend_income":"next time",
        "settlement":"Sign in",
        "times_the_movement_is_not_good":"multiple out of office",
        "my_performance_gains":"My performance gains",
        "quantity_of_undelivered_currency":"Number of unclaimed coins",
        "withdraw_money":"withdraw",
        "statistics":"statistics",
        "current_total_amount_of_grand_prize_pool":"total amount of the cloud",
        "current_total_amount_of_small_prize_pool":"total amount of the sea",
        "ticket_burn_rate":"Ticket burnout rate",
        "tickets_burned":"The ticket has been burned",
        "total_funds_invested":"Total funds invested",
        "total_settled_dividend_income":"Total paid dividend income",
        "total_recommended_revenue":"Total recommended revenue",
        "record":"record",
        "investment_record":"investment record",
        "withdrawals_record":"Withdrawal record",
        "my_sharing":"My share",
        "investment_amount":"investment amount",
        "consumption_tickets":"consumption of tickets",
        "investment_time":"investment time",
        "cash_withdrawal_amount":"to raise cash amount",
        "cash_withdrawal_time":"Cash time",
        "place_bind":"place bind parent",


        "address_error":"Address error",
        "network_error":"Please install the Huobi Wallet or imtoken wallet",
        "gt_0_01":"Must be greater than 0.01",
        "ticker_gt_100":"The number of tickets must be greater than 100",
        "withdraw_balance_gt_0_01":"Withdrawal amount must be greater than 0.01",
        "investment_success":"investment success",

    },
    {
        "name":"韩语",
        "starting_at":"韩语",
        "start_a_journey_of_legend":"韩语",
    },
    {
        "name":"日语",
        "starting_at":"日语",
        "start_a_journey_of_legend":"日语",
    },
    {
        "name":"俄语",
        "starting_at":"俄语",
        "start_a_journey_of_legend":"俄语",
    },
    {
        "name":"海雲傳奇",
        "starting_at":"開始於",
        "start_a_journey_of_legend":"開啟傳奇之旅",
        "bind_success":"綁定成功",
        "bind_error":"綁定失敗",
        "copy_success":"複製成功",
        "copy_error":"複製失敗",
        "balance_not_enough":"餘額不足",
        "buy_error":"購買失敗",
        "bind_parent":"綁定推薦人",
        "my_parent":"我的推薦人",
        "please_enter_the_address_of_the_recommend":"請輸入推薦人地址",
        "bind_immediately":"立即綁定",
        "invite_friends":"邀請好友",
        "invitation_link":"邀請鏈接",
        "immediate_participation":"立即參與",
        "investment_statement":"投資每日靜態分紅0.3-2.2%，推薦最高可得五倍收益",
        "play":"參與",
        "available":"可用",
        "send":"發送",
        "burning_ratio":"當前燃燒比例",
        "rule_1":"壹個賬號在出局前僅接受壹筆投資，出局後可繼續投資",
        "rule_2":"靜態分紅按照每天0.3%~2.2%上下浮動",
        "rule_3":"動靜出局，按照1-10為投資額3倍，11-30為投資額4倍，大於31為投資額5倍",
        "rule_4":"動態推薦25%按照:10%->8%->7%獲取動態獎勵，可即時提現",
        "rule_5":"小獎池達到指定時間後，小獎池不再沉澱，直到開啟下壹輪",
        "rule_6":"大獎池達到指定時間後，不再沉澱，投資額直接進入分紅收益",
        "play_rule":"玩法規則",
        "sign_in_success":"簽到成功",
        "sign_in_error":"簽到失敗",
        "withdraw_success":"提現成功",
        "withdraw_error":"提現失敗",
        "small_area_tip_1":"海區每",
        "small_area_tip_2":"小時開獎一次，100%開出。隨機50名平分獎池。",
        "big_area_tip_1":"雲區每",
        "big_area_tip_2":"小時開獎一次，100%開出。一等獎1名直接獲得獎池的1/3，二等獎10名平分獎池的1/3，三等獎20名平分獎池的1/3 。",
        "countdown_to_the_prize":"開獎倒計時",
        "total_amount_of_prize_pool":"獎池總金額",
        "buying_tickets":"購買門票",
        "purchase_admission_tickets":"購買入場門票",
        "purchase":"購買",
        "data_statistics":"數據統計",
        "my_income":"我的收益",
        "settled_dividend_income":"已結算分紅收益",
        "recommended_award":"推薦獎勵",
        "bonus_pool_revenue":"獎池收益",
        "time_difference_of_next_dividend_income":"下次分紅收益時間差",
        "settlement":"結算",
        "times_the_movement_is_not_good":"倍動靜出局還差",
        "my_performance_gains":"我的業績收益",
        "quantity_of_undelivered_currency":"未提幣數量",
        "withdraw_money":"提幣",
        "statistics":"統計",
        "current_total_amount_of_grand_prize_pool":"大獎池當前總量",
        "current_total_amount_of_small_prize_pool":"小獎池當前總量",
        "ticket_burn_rate":"門票焚毀倍率",
        "tickets_burned":"已焚毀門票",
        "total_funds_invested":"已投入的總資金",
        "total_settled_dividend_income":"總已結算分紅收益",
        "total_recommended_revenue":"總的推薦收益",
        "record":"記錄",
        "investment_record":"投資記錄",
        "withdrawals_record":"提現記錄",
        "my_sharing":"我的分享",
        "investment_amount":"投資金額",
        "consumption_tickets":"消耗門票",
        "investment_time":"投資時間",
        "cash_withdrawal_amount":"提現金額",
        "cash_withdrawal_time":"提現時間",
        "place_bind":"请先绑定推荐人",





        "address_error":"地址錯誤",
        "network_error":"請安裝火幣錢包或imToken錢包",
        "gt_0_01":"必須大於0.01",
        "ticker_gt_100":"門票數量必須大於100",
        "withdraw_balance_gt_0_01":"提幣金額必須大於0.01",
        "investment_success":"投資成功",
    }
];